spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: "root"
    password: "123456"

email:
  adminEmail: "wanghonghui_work@163.com"
  ccEmailList:
    - "850434439@qq.com"
